// Looping showcase videos in the Supabase Storage public `reels` bucket.
// Used by the homepage hero and Cams pages for each model's "live" video loop.
//
// Path: companion-<id>.mp4
// Generated by: npx vite-node scripts/generate-reels.ts -- --force
// That script takes each companion's current image_url (portrait) and
// image-to-videos it so the clip opens on the SAME face as the card.

const BASE = `${import.meta.env.VITE_SUPABASE_URL}/storage/v1/object/public/reels`;

// Legacy name map — unused. Kept so old imports don't break.
const REEL_MAP: Record<string, string> = {
  kaito: "r10",
  akira: "r11",
  sofia: "r1",
  aria: "r8",
  priya: "r3",
};

export const getCompanionReel = (_name: string | null | undefined): string | null => {
  return null;
};

export const companionForReel = (_reelName: string): string | null => null;

export const companionReelUrl = (id: string | null | undefined): string | null =>
  id ? `${BASE}/companion-${id}.mp4` : null;

// After a full portrait regen, ALL old clips can mismatch. Clear this set after
// you run: npx vite-node scripts/generate-reels.ts -- --force
// Add an id here only if that one clip is still wrong after regen.
const MISMATCHED_REELS = new Set<string>([
  // cleared — reels regenerated from current portraits
]);

export function getEffectiveCompanionReel(c: {
  id?: string;
  name?: string | null;
  gender?: string | null;
  created_by?: string | null;
}): string | null {
  if (!c || !c.id) return null;
  // User-created companions have no pre-recorded reel
  if (c.created_by) return null;
  if (MISMATCHED_REELS.has(c.id)) return null;
  return companionReelUrl(c.id);
}

function hash(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;
  return h;
}

// Stable pseudo viewer count so it doesn't jump on every render.
export function viewerCount(id: string): string {
  const n = 180 + (hash(id + "v") % 1400);
  return n >= 1000 ? `${(n / 1000).toFixed(1)}K` : `${n}`;
}
