import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { Link } from "@tanstack/react-router";

export const FAQS: { q: string; a: string }[] = [
  {
    q: "What is HumanCrush.com?",
    a: "HumanCrush.com is an AI companion platform where you can chat, flirt, and roleplay with realistic and anime AI characters. Build your own personality, exchange voice notes and AI selfies, and unlock spicy roleplay scenarios.",
  },
  {
    q: "Is HumanCrush.com free to use?",
    a: "Yes — every new account starts with 25 free messages, no credit card required. After that you can top up with credit packs or subscribe to Flirt, Lover, or Soulmate for unlimited daily chat plus bonus credits for selfies and voice notes.",
  },
  {
    q: "Can I create my own AI companion?",
    a: "Absolutely. Head to Create AI to design a character from scratch — pick gender, realistic or anime style, body type, hair, eyes, outfit, vibe, and personality traits like tone, interests, and boundaries. Your custom characters are private to your account.",
  },
  {
    q: "Are the conversations private?",
    a: "Yes. Your chats, custom characters, and memories are tied to your account and never shared. We don't sell your data, and you can delete your account and chat history at any time.",
  },
  {
    q: "Is HumanCrush.com suitable for adults?",
    a: "HumanCrush.com is designed for users 18 and older. You can engage in deep, personalized conversations and custom roleplay scenarios. You are always in control — set tone and boundaries per companion, and adjust them at any time from the chat header.",
  },
  {
    q: "How do credits and subscriptions work?",
    a: "Credits are used for messages, AI selfies, and voice notes. You can buy one-time credit packs or pick a monthly plan (Flirt, Lover, Soulmate) that includes a generous credit allowance and member perks. Subscriptions renew automatically and can be cancelled anytime.",
  },
  {
    q: "Will my companion remember me?",
    a: "Yes. Each companion has a memory system that stores key facts you share, plus a relationship level that grows as you chat. The deeper your bond, the more personal and intimate the conversations become.",
  },
  {
    q: "What payment methods are accepted?",
    a: "We accept all major credit and debit cards (Visa, Mastercard, American Express, Discover) processed securely through Authorize.Net. Your card details never touch our servers.",
  },
  {
    q: "Can I cancel my subscription?",
    a: "Yes, anytime. Go to your account settings and cancel in one click. You keep access until the end of your current billing period, and any remaining credit-pack balance stays on your account.",
  },
  {
    q: "Are the AI characters real people?",
    a: "No. Every character on HumanCrush.com — face, voice, and personality — is generated by AI. They are fictional and do not depict real individuals.",
  },
];

export function FAQSection() {
  const [open, setOpen] = useState<number | null>(0);
  return (
    <section className="mx-auto max-w-3xl px-4 py-16 md:py-24">
      <div className="text-center">
        <h2 className="font-display text-3xl font-semibold md:text-5xl">
          Frequently asked questions
        </h2>
        <p className="mt-3 text-sm text-muted-foreground md:text-base">
          Everything you need to know before you start flirting.
        </p>
      </div>

      <div className="mt-10 divide-y divide-white/10 rounded-2xl border border-white/10 bg-white/[0.02] backdrop-blur">
        {FAQS.map((item, i) => {
          const isOpen = open === i;
          return (
            <div key={i}>
              <button
                type="button"
                onClick={() => setOpen(isOpen ? null : i)}
                className="flex w-full items-center justify-between gap-4 px-5 py-5 text-left transition hover:bg-white/[0.03] md:px-6"
                aria-expanded={isOpen}
              >
                <span className="font-medium text-foreground md:text-lg">
                  {item.q}
                </span>
                <ChevronDown
                  className={`h-5 w-5 shrink-0 text-primary transition-transform duration-300 ${
                    isOpen ? "rotate-180" : ""
                  }`}
                />
              </button>
              <div
                className={`grid overflow-hidden px-5 transition-all duration-300 md:px-6 ${
                  isOpen ? "grid-rows-[1fr] pb-5" : "grid-rows-[0fr]"
                }`}
              >
                <div className="min-h-0">
                  <p className="text-sm leading-relaxed text-muted-foreground md:text-base">
                    {item.a}
                  </p>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      <div className="mt-8 text-center text-sm text-muted-foreground">
        Still have a question?{" "}
        <Link to="/faq" className="text-primary hover:underline">
          See all FAQs →
        </Link>
      </div>
    </section>
  );
}
