/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MeRouteImport } from './routes/me'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as CreateRouteImport } from './routes/create'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CamsIndexRouteImport } from './routes/cams.index'
import { Route as CompanionIdRouteImport } from './routes/companion.$id'
import { Route as ChatConversationIdRouteImport } from './routes/chat.$conversationId'
import { Route as CamsIdRouteImport } from './routes/cams.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicRunpodWebhookRouteImport } from './routes/api/public/runpod-webhook'
import { Route as ApiPublicAuthnetWebhookRouteImport } from './routes/api/public/authnet-webhook'
import { Route as ApiCronReengageRouteImport } from './routes/api/cron/reengage'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CamsIndexRoute = CamsIndexRouteImport.update({
  id: '/cams/',
  path: '/cams/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionIdRoute = CompanionIdRouteImport.update({
  id: '/companion/$id',
  path: '/companion/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const CamsIdRoute = CamsIdRouteImport.update({
  id: '/cams/$id',
  path: '/cams/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRunpodWebhookRoute = ApiPublicRunpodWebhookRouteImport.update({
  id: '/api/public/runpod-webhook',
  path: '/api/public/runpod-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthnetWebhookRoute = ApiPublicAuthnetWebhookRouteImport.update({
  id: '/api/public/authnet-webhook',
  path: '/api/public/authnet-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronReengageRoute = ApiCronReengageRouteImport.update({
  id: '/api/cron/reengage',
  path: '/api/cron/reengage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/create': typeof CreateRoute
  '/credits': typeof CreditsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/me': typeof MeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cams/$id': typeof CamsIdRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/companion/$id': typeof CompanionIdRoute
  '/cams/': typeof CamsIndexRoute
  '/api/cron/reengage': typeof ApiCronReengageRoute
  '/api/public/authnet-webhook': typeof ApiPublicAuthnetWebhookRoute
  '/api/public/runpod-webhook': typeof ApiPublicRunpodWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/create': typeof CreateRoute
  '/credits': typeof CreditsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/me': typeof MeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cams/$id': typeof CamsIdRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/companion/$id': typeof CompanionIdRoute
  '/cams': typeof CamsIndexRoute
  '/api/cron/reengage': typeof ApiCronReengageRoute
  '/api/public/authnet-webhook': typeof ApiPublicAuthnetWebhookRoute
  '/api/public/runpod-webhook': typeof ApiPublicRunpodWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/create': typeof CreateRoute
  '/credits': typeof CreditsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/me': typeof MeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/cams/$id': typeof CamsIdRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/companion/$id': typeof CompanionIdRoute
  '/cams/': typeof CamsIndexRoute
  '/api/cron/reengage': typeof ApiCronReengageRoute
  '/api/public/authnet-webhook': typeof ApiPublicAuthnetWebhookRoute
  '/api/public/runpod-webhook': typeof ApiPublicRunpodWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/create'
    | '/credits'
    | '/faq'
    | '/gallery'
    | '/history'
    | '/me'
    | '/reset-password'
    | '/admin'
    | '/cams/$id'
    | '/chat/$conversationId'
    | '/companion/$id'
    | '/cams/'
    | '/api/cron/reengage'
    | '/api/public/authnet-webhook'
    | '/api/public/runpod-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/create'
    | '/credits'
    | '/faq'
    | '/gallery'
    | '/history'
    | '/me'
    | '/reset-password'
    | '/admin'
    | '/cams/$id'
    | '/chat/$conversationId'
    | '/companion/$id'
    | '/cams'
    | '/api/cron/reengage'
    | '/api/public/authnet-webhook'
    | '/api/public/runpod-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/browse'
    | '/create'
    | '/credits'
    | '/faq'
    | '/gallery'
    | '/history'
    | '/me'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/cams/$id'
    | '/chat/$conversationId'
    | '/companion/$id'
    | '/cams/'
    | '/api/cron/reengage'
    | '/api/public/authnet-webhook'
    | '/api/public/runpod-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  CreateRoute: typeof CreateRoute
  CreditsRoute: typeof CreditsRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  HistoryRoute: typeof HistoryRoute
  MeRoute: typeof MeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CamsIdRoute: typeof CamsIdRoute
  ChatConversationIdRoute: typeof ChatConversationIdRoute
  CompanionIdRoute: typeof CompanionIdRoute
  CamsIndexRoute: typeof CamsIndexRoute
  ApiCronReengageRoute: typeof ApiCronReengageRoute
  ApiPublicAuthnetWebhookRoute: typeof ApiPublicAuthnetWebhookRoute
  ApiPublicRunpodWebhookRoute: typeof ApiPublicRunpodWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cams/': {
      id: '/cams/'
      path: '/cams'
      fullPath: '/cams/'
      preLoaderRoute: typeof CamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion/$id': {
      id: '/companion/$id'
      path: '/companion/$id'
      fullPath: '/companion/$id'
      preLoaderRoute: typeof CompanionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cams/$id': {
      id: '/cams/$id'
      path: '/cams/$id'
      fullPath: '/cams/$id'
      preLoaderRoute: typeof CamsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/runpod-webhook': {
      id: '/api/public/runpod-webhook'
      path: '/api/public/runpod-webhook'
      fullPath: '/api/public/runpod-webhook'
      preLoaderRoute: typeof ApiPublicRunpodWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/authnet-webhook': {
      id: '/api/public/authnet-webhook'
      path: '/api/public/authnet-webhook'
      fullPath: '/api/public/authnet-webhook'
      preLoaderRoute: typeof ApiPublicAuthnetWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reengage': {
      id: '/api/cron/reengage'
      path: '/api/cron/reengage'
      fullPath: '/api/cron/reengage'
      preLoaderRoute: typeof ApiCronReengageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  CreateRoute: CreateRoute,
  CreditsRoute: CreditsRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  HistoryRoute: HistoryRoute,
  MeRoute: MeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CamsIdRoute: CamsIdRoute,
  ChatConversationIdRoute: ChatConversationIdRoute,
  CompanionIdRoute: CompanionIdRoute,
  CamsIndexRoute: CamsIndexRoute,
  ApiCronReengageRoute: ApiCronReengageRoute,
  ApiPublicAuthnetWebhookRoute: ApiPublicAuthnetWebhookRoute,
  ApiPublicRunpodWebhookRoute: ApiPublicRunpodWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
